# Generated by Django 5.1 on 2024-09-27 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0002_receipe_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipe',
            name='rating',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
