# Generated by Django 5.1 on 2024-09-27 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0005_alter_receipe_rating1_rename_rating1_receipe_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipe',
            name='rating',
        ),
        migrations.AddField(
            model_name='receipe',
            name='rating2',
            field=models.IntegerField(blank=True, db_column='rating1', default=0, null=True),
        ),
    ]
