# Generated by Django 5.1 on 2024-09-27 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0006_remove_receipe_rating_receipe_rating2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipe',
            name='rating2',
        ),
        migrations.AddField(
            model_name='receipe',
            name='rating',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
