# Generated by Django 5.1 on 2024-09-27 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0008_alter_receipe_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipe',
            name='rating',
        ),
        migrations.AddField(
            model_name='receipe',
            name='rating_2',
            field=models.IntegerField(blank=True, db_column='new_rating', default=0, null=True),
        ),
    ]
