# Generated by Django 5.1 on 2024-09-27 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0011_remove_receipe_rating_receipe_rating1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipe',
            name='rating1',
        ),
        migrations.AddField(
            model_name='receipe',
            name='rating_new',
            field=models.IntegerField(blank=True, db_column='rating1', default=0, null=True),
        ),
    ]
