# Generated by Django 5.1 on 2024-09-27 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0012_remove_receipe_rating1_receipe_rating_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipe',
            name='rating_new',
        ),
        migrations.AddField(
            model_name='receipe',
            name='rating',
            field=models.IntegerField(blank=True, db_column='rating_new', default=0, null=True),
        ),
    ]
