# Generated by Django 5.1 on 2024-10-03 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0013_remove_receipe_rating_new_receipe_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipe',
            name='rating',
            field=models.IntegerField(blank=True, db_column='rating', default=0, null=True),
        ),
    ]
