# Generated by Django 5.1 on 2024-10-03 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0016_alter_receipe_rating1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipe',
            old_name='rating1',
            new_name='rating11',
        ),
    ]
