# Generated by Django 5.1 on 2024-10-03 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0017_rename_rating1_receipe_rating11'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipe',
            name='rating11',
        ),
        migrations.AddField(
            model_name='receipe',
            name='rating111',
            field=models.IntegerField(blank=True, db_column='rating11', default=0, null=True),
        ),
    ]
